create table if not exists public.coach_dashboards (
  id bigint generated by default as identity primary key,
  clerk_user_id text not null unique,
  dashboard jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists coach_dashboards_clerk_user_id_idx
  on public.coach_dashboards (clerk_user_id);
